<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-PdfReader.Worker-55933b43-c95e-49ba-8e8d-2cf2c7b96afc</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="9.1.0" />
        <PackageReference Include="MassTransit.AspNetCore" Version="7.3.1" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="9.1.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\PdfReader.Infrastructure\PdfReader.Infrastructure.csproj" />
    </ItemGroup>
</Project>
